apiVersion: apps/v1
kind: Deployment        # Deploy metadata
metadata:
  name: ui
  labels:
    app: reddit
    component: ui
spec:                   # Deploy specification
  replicas: 3
  selector:
    matchLabels:
      app: reddit
      component: ui
  template:             # Pod description
    metadata:
      name: ui-pod
      labels:
        app: reddit
        component: ui
    spec:
      containers:
      - image: skyfly534/ui
        name: ui
