- name: Gitlab CI deployment in Docker
  hosts: all
  become: yes
  tasks:

    - name: create dirs for data volumes
      file:
        name: "{{ item }}"
        state: directory
        owner: root
        group: root
      with_items:
        - "/srv/gitlab/config"
        - "/srv/gitlab/logs"
        - "/srv/gitlab/data"

    - name: install PIP
      apt:
        name: python3-pip
        state: present

    - name: install Docker
      pip:
        name: docker
        state: present

    - name: Gitlab CI deployment in Docker
      community.docker.docker_container:
        name: gitlab
        hostname: gitlab
        image: gitlab/gitlab-ce:15.4.0-ce.0
        state: started
        restart_policy: unless-stopped
        container_default_behavior: "no_defaults"
        env:
          GITLAB_OMNIBUS_CONFIG: "external_url \"http://{{ ansible_host }}\""
        ports:
          - "80:80"
          - "443:443"
          - "2222:22"
        volumes:
          - "/srv/gitlab/config:/etc/gitlab"
          - "/srv/gitlab/logs:/var/log/gitlab"
          - "/srv/gitlab/data:/var/opt/gitlab"
